# First action
name: First action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ansible-node
    steps:
      - name: Print greeting
        run: |
            echo "Helllo World!"
            echo "Helllo Second Line!"
      - name: Print Goodbye
        run: echo "Done - Bye!"
